/* This file was generated by the md5table tool. DO NOT EDIT!
 */
/*
struct MD5Table {
	const char *md5;
	const char *target;
	Common::Language language;
	Common::Platform platform;
};

static const MD5Table md5table[] = {
	{ "4cb9c3618f71668f8e4346c8f323fa82", "monkey2", Common::EN_USA, Common::kPlatformMacintosh },
	{ "132bff65e6367c09cc69318ce1b59333", "monkey2", Common::EN_USA, Common::kPlatformAmiga },
	{ "11ddf1fde76e3156eb3a38da213f484e", "monkey2", Common::IT_ITA, Common::kPlatformAmiga },
	{ "6ea966b4d660c870b9ee790d1fbfc535", "monkey2", Common::ES_ESP, Common::kPlatformAmiga },
	{ "c30ef068add4277104243c31ce46c12b", "monkey2", Common::FR_FRA, Common::kPlatformAmiga },
	{ "da669b20271b85182e9c17a2a37ea02e", "monkey2", Common::DE_DEU, Common::kPlatformAmiga },
	{ "3686cf8f89e102ececf4366e1d2c8126", "monkey2", Common::EN_USA, Common::kPlatformPC },
	{ "6886e5d08cee329b1f2e743ae2e3ceed", "monkey2", Common::DE_DEU, Common::kPlatformPC },
	{ "69ea626f1f87eecb78ea0d6c6b983a1d", "monkey2", Common::IT_ITA, Common::kPlatformPC },
	{ "bd126753de619a495f9f22adc951c8d5", "monkey2", Common::IT_ITA, Common::kPlatformPC },
	{ "7974365d3dc0f43a2748c975f91ff042", "monkey2", Common::ES_ESP, Common::kPlatformPC },
	{ "8e4ee4db46954bfe2912e259a16fad82", "monkey2", Common::FR_FRA, Common::kPlatformPC },

	{ "d6dd0646404768a63e963891a96daadd", "atlantis", Common::EN_USA, Common::kPlatformMacintosh },
	{ "3a03dab514e4038df192d8a8de469788", "atlantis", Common::EN_USA, Common::kPlatformAmiga },
	{ "4f267a901719623de7dde83e47d5b474", "atlantis", Common::DE_DEU, Common::kPlatformAmiga },
	{ "5798972220cd458be2626d54c80f71d7", "atlantis", Common::IT_ITA, Common::kPlatformAmiga },
	{ "c63ee46143ba65f9ce14cf539ca51bd7", "atlantis", Common::EN_USA, Common::kPlatformPC },
	{ "8f3758ff98c9c5d78e5d635222cad026", "atlantis", Common::IT_ITA, Common::kPlatformPC },
	{ "182344899c2e2998fca0bebcd82aa81a", "atlantis", Common::EN_USA, Common::kPlatformPC },
	{ "1fbebd7b2b692df5297870447a80cfed", "atlantis", Common::DE_DEU, Common::kPlatformPC },
	{ "9bd2a8f72613e715c199246dd511e10f", "atlantis", Common::ES_ESP, Common::kPlatformPC },
	{ "edfdb24a499d92c59f824c52987c0eec", "atlantis", Common::FR_FRA, Common::kPlatformPC },
	
	{ "2723fea3dae0cb47768c424b145ae0e7", "tentacle", Common::EN_USA, Common::kPlatformPC },
	{ "4167a92a1d46baa4f4127d918d561f88", "tentacle", Common::EN_USA, Common::kPlatformUnknown },
	{ "4fbbe9f64b8bc547503a379a301183ce", "tentacle", Common::IT_ITA, Common::kPlatformUnknown },
	{ "50fcdc982a25063b78ad46bf389b8e8d", "tentacle", Common::IT_ITA, Common::kPlatformPC },
	{ "57b0d89af79befe1cabce3bece869e7f", "tentacle", Common::DE_DEU, Common::kPlatformPC },
	{ "6e959d65358eedf9b68b81e304b97fa4", "tentacle", Common::DE_DEU, Common::kPlatformUnknown },
	{ "883af4b0af4f77a92f1dcf1d0a283140", "tentacle", Common::ES_ESP, Common::kPlatformUnknown },
	{ "8aa05d3cdb0e795436043f0546af2da2", "tentacle", Common::FR_FRA, Common::kPlatformUnknown },
	{ "92b078d9d6d9d751da9c26b8b3075779", "tentacle", Common::FR_FRA, Common::kPlatformPC },
	{ "acad97ab1c6fc2a5b2d98abf6db4a190", "tentacle", Common::EN_USA, Common::kPlatformUnknown },
	{ "ae94f110a14ce71fc515d5b648827a8f", "tentacle", Common::ES_ESP, Common::kPlatformPC },

	{ "3b301b7892f883ce42ab4be6a274fea6", "samnmax", Common::EN_USA, Common::kPlatformPC },
	{ "ef347474f3c7be3b29584eaa133cca05", "samnmax", Common::FR_FRA, Common::kPlatformPC },
	{ "f27b1ba0eadaf2a6617b2b58192d1dbf", "samnmax", Common::DE_DEU, Common::kPlatformPC },
	{ "fc53ce0e5f6562b1c1e1b4b8203acafb", "samnmax", Common::ES_ESP, Common::kPlatformPC },
	{ "0f6f2e716ba896a44e5059bba1de7ca9", "samnmax", Common::IT_ITA, Common::kPlatformUnknown },
	{ "0fb73eddfcf584c02ba097984df131ba", "samnmax", Common::DE_DEU, Common::kPlatformUnknown },
	{ "4ba7fb331296c283e73d8f5b2096e551", "samnmax", Common::ES_ESP, Common::kPlatformUnknown },
	{ "7edd665bbede7ea8b7233f8e650be6f8", "samnmax", Common::FR_FRA, Common::kPlatformUnknown },
	{ "a3036878840720fbefa41e6965fa4a0a", "samnmax", Common::EN_USA, Common::kPlatformPC },
	{ "b289a2a8cbedbf45786e0b4ad2f510f1", "samnmax", Common::IT_ITA, Common::kPlatformPC },
	{ "d917f311a448e3cc7239c31bddb00dd2", "samnmax", Common::EN_USA, Common::kPlatformUnknown },

	{ 0, 0, Common::UNK_LANG, Common::kPlatformUnknown }
};
*/