/*  linker.h -- MiNTLib.
    Copyright (C) 2000 Guido Flohr <guido@freemint.de>

    This file is part of the MiNTLib project, and may only be used
    modified and distributed under the terms of the MiNTLib project
    license, COPYMINT.  By continuing to use, modify, or distribute
    this file you indicate that you have read the license and
    understand and accept it fully.
*/

/* ATTENTION: This file is generated by the MiNTLib. Do not edit!  */

#ifndef	_LINKER_H
# define _LINKER_H 1

#define __LINKER_TYPE __GNU

#if __LINKER_TYPE == __GNU
# define __HAVE_GNU_LD
#else 
# if __LINKER_TYPE == __OLD_GNU
#  define __HAVE_OLDGNU_LD  /* Currently not used.  */
# else
#   error Unknown linker.
# endif
#endif

#endif /* _LINKER_H  */
